<?php
include_once '../libs/gsi/api/APIController.php';

class MASGAUExport extends APIController {
    
    public function __construct($gamelink) {
        parent::__construct($gamelink);
        
    }
    private $xml_versions = array(
        "MASGAU11"=>array(),
        "GameSaveInfo20"=>array(),
        "GameSaveInfo202"=>array()
        );


    protected function drawExporterList() {
        $title = 'MASGAU Auto-Update';
        
        echo '<html><head>'."\n";
        echo '<title>'.$title.'</title>'."\n";
        echo '<META NAME="robots" CONTENT="noindex,nofollow,noarchive">';
        //echo '<script type="text/javascript" src="../libs/jquery/jquery-1.7.2.min.js"></script>'."\n";
        //echo '<script type="text/javascript" src="../libs/flot/jquery.flot.js"></script>'."\n";
        
        
        
        
        
        echo '</head><body>'."\n";
        
         //echo '<div id="placeholder" style="width:600px;height:300px;float:right;border:solid 1px black;"></div>'."\n";
        
        echo '<h1>'.$title.'</h1>'."\n";
        
        echo "Exporter not specified, available options:"."\n";
        echo "<ul>\n";
        
        $usage_stats = array();
        
        foreach(array_keys($this->xml_versions) as $exporter) {
          echo '<li><details>';
          echo '<summary><a href="/updates/'.$exporter.'/">'.$exporter.'</a></summary>'."\n";
          $class = $exporter.'UpdateList';

            $exporter_stats = array();
            
            include_once $class.'.php';
            $exp = new $class(null,null);
            echo '<ul>'."\n";
            $files =  $exp->getFiles();
            
            foreach(array_keys($files) as $file) {
              echo '<li><a href="/updates/'.$exporter.'/'.$file.'">'.$file.'</a></li>'."\n";
//                $usages = $this->link->RunStatement("SELECT MAX(count) as MAX, timestamp FROM export_statistics WHERE exporter = '".$exporter."' 
  //              AND criteria = '".$files[$file]["criteria"]."' GROUP BY timestamp ORDER BY timestamp DESC LIMIT 0, 5 ");
    //            foreach($usages as $usage) {
      //              if(!array_key_exists($usage->timestamp,$exporter_stats)||
        //                    $exporter_stats[$usage->timestamp]<$usage->MAX) {
          //              $exporter_stats[$usage->timestamp] = $usage->MAX;
            //        }
              //  }
            }
            
            echo '</ul>'."\n";
            echo '</details></li>'."\n";
            
//            $usage_stats[$exporter] = $exporter_stats;

        }
        echo "</ul>";
  /*      
        echo '<script type="text/javascript">
        
        
        
            $(document).ready(function() {
                $.plot($("#placeholder"), 
                ';
                echo '[ '."\n";
                foreach(array_keys($usage_stats) as $exporter) {
                    echo '[ '."\n";
                    $stats = $usage_stats[$exporter];
                    ksort($stats);
                    foreach(array_keys($stats) as $time) {
                        echo '['.strtotime($time).', '.$stats[$time].'], '."\n";
                    }
                    echo ' ], '."\n";
                }
                echo ' ]'."\n";
                
                echo ', { xaxis: { mode:"time", timeformat: "%y/%m/%d %H:%M:%S%p"} });
            });
        </script>';

        
    */    
         echo '</body></html>';
    }
    private $donotedit = "DO NOT EDIT THIS FILE, CHANGES WILL EVENTUALLY BE OVERWRITTEN BY THE AUTO UPDATE SYSTEM!";

    protected function export($exporter, $criteria = null, $comment = null, $date  = null) {
        if(is_null($criteria)) {
            include_once $exporter."UpdateList.php";
            $class = $exporter."UpdateList";
            $updates = new $class($this->link);
            $updates->drawPage();            
        } else {
          $class = $exporter.'UpdateList';          
            include_once $class.'.php';
            $exp = new $class(null,null);
            $files =  $exp->getFiles();
//                        var_dump($files);

            if(sizeof($files)==0) {
                throw new Exception("NO VALID FILE SPECIFIED: ".$criteria);
            }
            
            $file = $files[$criteria];
            
            header("Content-Disposition: inline; filename=\"".$criteria."\"");
            
            $update = $this->link->Select("update_history",null,null,"timestamp DESC");
            $update = $update[0];
            
          //  return;
            return parent::export($exporter,$file["criteria"],$file["comment"]."\n".$this->donotedit,$update->timestamp);
        }
    }

}

?>
